### ISSUE TITLE
Google Colab stops before processing the wile with this error

### ISSUE THREAD

**Issue by edo0** [hirios/Waifu2x-Colab#1]
Hi there!
First of all, thank you very much for your script to deploy Waifu2x on Google Colab.
I wanted to point out an error which hinders the execution on my Colab notebook instance.
If you could have a look into this and let me now what you think about it, I would be really grateful!
Obrigado!
```
Número de vezes que deseja ampliar: 2

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)

<ipython-input-4-9e6532bd3103> in <module>()
    121     video_upload()
    122     print_dir()
--> 123     get_fps()
    124     get_frames()
    125     upscale_frames()

<ipython-input-4-9e6532bd3103> in get_fps()
     57 
     58     fps = str(os.popen(f'ffmpeg -i "{caminho}{diretorio[novoindice]}" 2> fps.txt ; egrep -i "fps" fps.txt').read())
---> 59     fps = fps.split(",")[4].split()[0]
     60     get_ipython().system('rm "fps.txt"')
     61 

IndexError: list index out of range
```

**Comment by hirios** [comment]
Hello Friend!
Did you try with a different video file? This function is responsible for taking the video's fps using ffmpeg, but I didn't test it with several videos. I'll edit and leave a default fps, in case ffmpeg can't find it. If the synchronization of the video and audio is different, it is because of this. Give me feedback if you can make it work!

**Comment by hirios** [comment]
> Hi there!
> First of all, thank you very much for your script to deploy Waifu2x on Google Colab.
> I wanted to point out an error which hinders the execution on my Colab notebook instance.
> If you could have a look into this and let me now what you think about it, I would be really grateful!
> Obrigado!
> 
> ```
> Número de vezes que deseja ampliar: 2
> 
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> 
> <ipython-input-4-9e6532bd3103> in <module>()
>     121     video_upload()
>     122     print_dir()
> --> 123     get_fps()
>     124     get_frames()
>     125     upscale_frames()
> 
> <ipython-input-4-9e6532bd3103> in get_fps()
>      57 
>      58     fps = str(os.popen(f'ffmpeg -i "{caminho}{diretorio[novoindice]}" 2> fps.txt ; egrep -i "fps" fps.txt').read())
> ---> 59     fps = fps.split(",")[4].split()[0]
>      60     get_ipython().system('rm "fps.txt"')
>      61 
> 
> IndexError: list index out of range
> ```

I didn't do anything to check the progress. And the process takes a little time. If possible, from time to time move mouse in the tab, so that Google Collab does not end the process due to inactivity. This usually happens if there are 2 hours of inactivity.
When finished, the output file will be in your Google Drive

**Comment by hirios** [comment]
Remember to enable gpu support in Google Collab

**Comment by edo0** [comment]
Hi, thank you for getting back to me!
I was indeed missing the selection of GPU acceleration, and I apologize about that!

Now that I have it enabled, however, a different sort of stalemate happens:

```
Selecione o seu arquivo: 101

Número de vezes que deseja ampliar: 2

Extraindo frames e audio do seu vídeo...

Realizando upscale de cada imagem...
/content/waifu2x-chainer
/content

0 itens movidos para /content/upframes
/content/upframes

Gerando novo arquivo de vídeo...

==================== FIIIIIIIIIMMMMMMMMMMMM ====================

15:02:33
15:03:15

```

After this the python script finishes, but nothing seem to be generated on my drive
I have tried with both mkv and mp4 videos, anywhere between 5 seconds and 5 minutes long

**Comment by hirios** [comment]
Can you send me the video file you are trying to upscale?
If possible, do a test with this excerpt here:

https://drive.google.com/file/d/14eIJDxREVmQihnMnutRz06G398oeanOO/view?usp=sharing

**Comment by edo0** [comment]
I get the same result with the video you sent me as well

```
Selecione o seu arquivo: 102

Número de vezes que deseja ampliar: 2

Extraindo frames e audio do seu vídeo...

Realizando upscale de cada imagem...
/content/waifu2x-chainer
/content

0 itens movidos para /content/upframes
/content/upframes

Gerando novo arquivo de vídeo...

==================== FIIIIIIIIIMMMMMMMMMMMM ====================

20:11:53
20:12:52
```

This is the video I was testing on: https://drive.google.com/file/d/1ni6kU8QIezVMWUOhXa-VWU0pWvp-j30A/view?usp=sharing

**Comment by edo0** [comment]
Is there possibly any other dependency or setting I may be missing on?

**Comment by hirios** [comment]
I made this video:
https://www.youtube.com/watch?v=NsJdmTQENO4&feature=youtu.be

Sorry for the quality, I forgot to configure the OBS

**Comment by edo0** [comment]
Thank you!! 
So, I found another mistake I was doing: by selecting a folder number, I was expecting the content of the folder to be worked upon. As that is not the case, I am now putting the files to be worked upon in the main folder of google Drive.

I was able to successfully upscale the sample video you had sent me! :)

However, the first video I sent you (https://drive.google.com/file/d/1ni6kU8QIezVMWUOhXa-VWU0pWvp-j30A/view?usp=sharing), as well as this other one
https://drive.google.com/file/d/1TqVzy9YWRjM52lBGxZwow8oGjgmHxFeN/view?usp=sharing

seem to process fine (see output below), but after the conversion [I briefly see the folder containing the upscaled frames] no video is generated in my Google Drive (while with same circumstances, the anime you sent me works alright)

```
Selecione o seu arquivo: 106

Número de vezes que deseja ampliar: 2

Extraindo frames e audio do seu vídeo...

Realizando upscale de cada imagem...
/content/waifu2x-chainer
/content

311 itens movidos para /content/upframes
/content/upframes

Gerando novo arquivo de vídeo...

==================== FIIIIIIIIIMMMMMMMMMMMM ====================

23:32:28
23:43:37
```

Tomorrow morning I can send you a video, if you think it may help!! :)

**Comment by hirios** [comment]
I think I found the problem that was occurring with your videos. The .aac extraction failed. I think I managed to correct it.

**Comment by edo0** [comment]
The first video (w/ rice and cello case) now upscales correctly! https://drive.google.com/file/d/1UHnifKY74MpXiRDXDTll7jOyfDX36Bfy/view?usp=sharing

Unfortunately the second file still won't be correctly turned into a video
https://drive.google.com/file/d/1TqVzy9YWRjM52lBGxZwow8oGjgmHxFeN/view?usp=sharing

**Comment by hirios** [comment]
I think it will work now. Again problem with fps. I saw that you're trying to upscale videos with real people. Perhaps the result is not so good. But nothing stops him from trying. Sometimes it looks good!

**Comment by edo0** [comment]
Thank you very much, now it does work perfectly with any sort of clips I have been feeding it.
Indeed, I plan to use it with both animation and some actual real-life footage: obviously waifu2x is targeted to and optimized for anime, but also real-life videos come out pretty good on it! - and better than with normal upscaling algorithms.

Thank you so much for all the help you gave me with it!!

**Comment by hirios** [comment]
I thank you for the feedback! I'm glad someone is using a script of mine.
