### ISSUE TITLE
list index out of range with video without audio

### ISSUE THREAD

**Issue by gioolio** [hirios/Waifu2x-Colab#2]
It gives a "_list index out of range_" error when I try to scale a video without audio.
I solved it by checking the length of the variable "size" before using it.
my solution:
```
def get_audio():
  print("Extraindo audio ...")
  os.system(f"""ffmpeg -i "{caminho}{diretorio[novoindice]}" -vn -acodec copy /content/audio.aac""")
  size = !du -sh /content/audio.aac  2>/dev/null
  **if len(size)!=0:**
    if size[0].split()[0] == '0':
      !rm /content/audio.aac
      !ffmpeg -i  "{caminho}{diretorio[novoindice]}" -vn -ac 2 -ar 44100 -ab 320k -f mp3 /content/audio.aac  2>/dev/null
```
I'm not sure if generating_video2x(): will work even when a audio.aac is empty.
If not, a os.remove() could be added in get_audio() under the condition else of the proposed solution

**Comment by hirios** [comment]
@gioolio First of all, thank you very much for the feedback, when I have time I will test some video without audio.

As for the ```generating_video2x()``` function, you can remove this ```-i /content/audio.aac```, in case the way you did it goes wrong.
